/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import com.Messages;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LasithaRanawaka
 */
public class GrnTempView extends javax.swing.JFrame {

    /**
     * Creates new form ginPart2
     */
    public GrnTempView() {
        initComponents();
        FirstLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_GinPart2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Invoices");

        tbl_GinPart2.setBackground(new java.awt.Color(255, 204, 204));
        tbl_GinPart2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice No", "Date", "Cus Name", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_GinPart2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_GinPart2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_GinPart2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_GinPart2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_GinPart2MouseClicked
        if (tbl_GinPart2.getRowCount() != 0) {

            if (evt.getClickCount() == 2) {
                int id=Integer.parseInt(tbl_GinPart2.getValueAt(tbl_GinPart2.getSelectedRow(), 0).toString());
                new InvoiceReturn(id).setVisible(true);

            }
        }
    }//GEN-LAST:event_tbl_GinPart2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrnTempView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrnTempView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrnTempView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrnTempView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrnTempView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tbl_GinPart2;
    // End of variables declaration//GEN-END:variables

    private void FirstLoad() {

        LoadAllPendinghs();

    }
    String todaydate = "";

    private void today() {
        Date datenow = new Date();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        StringBuilder sb = new StringBuilder(sdf.format(datenow));
        todaydate = datenow.toString();


    }

    public static void LoadAllPendinghs() {

        try {
            DefaultTableModel tb = (DefaultTableModel) tbl_GinPart2.getModel();
            tb.setRowCount(0);


            try {

                ResultSet rs = model.db.fetch("SELECT\n"
                        + "ginreg.id,\n"
                        + "ginreg.date,\n"
                        + "customer.`name`,\n"
                        + "ginreg.total\n"
                        + "FROM\n"
                        + "ginreg ,\n"
                        + "customer\n"
                        + "WHERE\n"
                        + "ginreg.customer_id = customer.id AND\n"
                        + "ginreg.`status` = '0'");

                while (rs.next()) {

                    String id = rs.getString(1);
                    Date date = rs.getDate(2);
                    String total = rs.getString(3);
                    String disc = rs.getString(4);


                    Object arr[] = {id, date, total, disc};
                    tb.addRow(arr);
                }


            } catch (Exception e) {
                e.printStackTrace();
            }


        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
